### ISSUE TITLE
What is that about wrap-cors? 

### ISSUE THREAD

**Issue by pdenno** [replikativ/datahike-frontend#1]
Hi, 
I know you are just getting started with this, but it mostly worked out of the box so I am encouraged. However, I don't understand what the README is saying about wrap-cors. There is no server.clj, and the only wrap-cors I found was in ring-cors. When I included that in deps.edn and evaluated the wrap-cors line shown in the README, it didn't like. 

I'm not familiar with ring. Perhaps the answer is really obvious.

**Comment by grischoun** [comment]
Hi @pdenno 

Actually, if you just checkout the 'admin-endpoints' branch of datahike-server, you can then forget about CORS issue. (It is fixed there already.)
